using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Playables;
using UnityEngine.Serialization;

namespace FluidFrenzy
{
	/// <summary>
	/// A <see cref="ScriptableObject"/> asset containing configuration parameters for a <see cref="FoamLayer"/>.
	/// </summary>
	/// <remarks>
	/// Using a settings asset allows for easy reuse and centralized modification of foam behaviors across multiple <see cref="FoamLayer"/> instances.
	/// <para>
	/// To create a new settings asset, navigate to: <c>Assets > Create > Fluid Frenzy > Foam Layer Settings</c>.
	/// </para>
	/// </remarks>
	[CreateAssetMenu(fileName = "Foam Settings", menuName = "FluidSimulation/Foam Settings", order = 51)]
	[HelpURL("https://frenzybyte.github.io/fluidfrenzy/docs/fluid_simulation_components/#foam-layer-settings")]
	public class FoamLayerSettings : ScriptableObject, ISerializationCallbackReceiver
	{
		[SerializeField]
		internal int version = 1;

		/// <summary>
		/// The resolution of the generated foam mask texture.
		/// </summary>
		/// <remarks>
		/// Higher resolutions provide sharper foam details but require more memory and GPU processing power. 
		/// It is generally recommended to match the aspect ratio of the fluid simulation grid.
		/// </remarks>
		public Vector2Int textureSize = new Vector2Int(512, 512);

		/// <summary>
		/// Toggles the generation of foam based on internal fluid pressure.
		/// </summary>
		/// <remarks>
		/// <b>Note:</b> This feature is strictly for use with <see cref="FluxFluidSimulation"/>. The alternative <see cref="FlowFluidSimulation"/> does not calculate internal pressure fields, so enabling this will have no effect in that mode.
		/// </remarks>
		public bool applyPressureFoam = true;

		/// <summary>
		/// Defines the pressure threshold range for foam generation.
		/// </summary>
		/// <remarks>
		/// <list type="bullet">
		/// 	<item>
		/// 		<term>X (Min)</term>
		/// 		<description>Pressure values below this threshold generate no foam.</description>
		/// 	</item>
		/// 	<item>
		/// 		<term>Y (Max)</term>
		/// 		<description>Pressure values above this threshold generate the maximum amount of foam.</description>
		/// 	</item>
		/// </list>
		/// Intermediate values are interpolated using <see href="https://en.wikipedia.org/wiki/Smoothstep">Smoothstep</see>.
		/// </remarks>
		public Vector2 pressureRange = new Vector2(0.4208788f, 0.6301731f);

		/// <summary>
		/// The rate at which foam accumulates per frame when fluid pressure exceeds the <see cref="pressureRange"/> minimum.
		/// </summary>
		public float pressureIncreaseAmount = 0.5f;

		/// <summary>
		/// The rate at which pressure-based foam decays exponentially per frame.
		/// </summary>
		/// <remarks>
		/// Higher values cause the foam to dissipate more rapidly. This affects foam generated by the pressure system.
		/// </remarks>
		[FormerlySerializedAs("pressureExponentialDecayRate")]
		public float exponentialDecayRate = 0.1f;

		/// <summary>
		/// The constant amount of pressure-based foam subtracted from the mask per frame (Linear Decay).
		/// </summary>
		[FormerlySerializedAs("pressureLinearDecayRate")]
		public float linearDecayRate = 0;


		/// <summary>
		/// Toggles the generation of foam based on wave geometry (height and steepness).
		/// </summary>
		/// <remarks>
		/// This system simulates whitecaps and crest foam caused by turbulent or high-amplitude waves.
		/// </remarks>
		public bool applyWaveFoam = true;

		/// <summary>
		/// Defines the wave surface angle (steepness) thresholds for foam generation.
		/// </summary>
		/// <remarks>
		/// <list type="bullet">
		/// 	<item>
		/// 		<term>X (Min)</term>
		/// 		<description>Wave angles below this value generate no foam.</description>
		/// 	</item>
		/// 	<item>
		/// 		<term>Y (Max)</term>
		/// 		<description>Wave angles above this value generate maximum foam.</description>
		/// 	</item>
		/// </list>
		/// Intermediate values are interpolated using <see href="https://en.wikipedia.org/wiki/Smoothstep">Smoothstep</see>.
		/// </remarks>
		public Vector2 waveAngleRange = new Vector2(0, 0.2461978f);

		/// <summary>
		/// The amount of foam added per frame when the wave angle exceeds the <see cref="waveAngleRange"/> minimum.
		/// </summary>
		public float waveAngleIncreaseAmount = 0.25f;

		/// <summary>
		/// The amount of foam added per frame based on the vertical (Y) velocity of the fluid surface.
		/// </summary>
		/// <remarks>
		/// This simulates foam generated by rapidly rising water, such as splashes or chaotic wave peaks.
		/// </remarks>
		public float waveHeightIncreaseAmount = 0.5f;

		/// <summary>
		/// The rate at which wave-based foam decays exponentially per frame.
		/// </summary>
		[SerializeField]
		private float waveExponentialDecayRate = 0.132f;

		/// <summary>
		/// The constant amount of wave-based foam subtracted from the mask per frame (Linear Decay).
		/// </summary>
		[SerializeField]
		private float waveLinearDecayRate = 0.05f;


		/// <summary>
		/// Toggles the generation of foam in shallow water areas where fluid velocity is high.
		/// </summary>
		/// <remarks>
		/// This is useful for simulating shorelines or river rapids where water churns against the ground.
		/// </remarks>
		public bool applyShallowFoam = false;

		/// <summary>
		/// The maximum intensity of foam added when the shallow water criteria are met.
		/// </summary>
		public float shallowFoamAmount = 1;

		/// <summary>
		/// Defines the velocity range required to generate foam in shallow water.
		/// </summary>
		/// <remarks>
		/// <list type="bullet">
		/// 	<item>
		/// 		<term>X (Min)</term>
		/// 		<description>Fluid speeds below this value generate no foam, even if the water is shallow.</description>
		/// 	</item>
		/// 	<item>
		/// 		<term>Y (Max)</term>
		/// 		<description>Fluid speeds above this value generate maximum foam.</description>
		/// 	</item>
		/// </list>
		/// Intermediate values are interpolated using <see href="https://en.wikipedia.org/wiki/Smoothstep">Smoothstep</see>.
		/// </remarks>
		public Vector2 shallowVelocityRange = new Vector2(0, 10);

		/// <summary>
		/// The depth threshold for shallow water foam.
		/// </summary>
		/// <remarks>
		/// Foam will only be generated in areas where the fluid depth is less than this value (and velocity requirements are met).
		/// </remarks>
		public float shallowDepth;


		/// <summary>
		/// Toggles the generation of foam based on velocity gradients (turbulence).
		/// </summary>
		/// <remarks>
		/// Calculates foam based on the curl or difference in velocity vectors between adjacent cells.
		/// </remarks>
		public bool applyTurbulenceFoam = false;

		/// <summary>
		/// The intensity multiplier for foam generated by turbulence.
		/// </summary>
		public float turbulenceFoamAmount = 1;

		/// <summary>
		/// The minimum turbulence value required to begin generating foam.
		/// </summary>
		public float turbulenceFoamThreshold = 0.1f;

		public void OnAfterDeserialize()
		{
			exponentialDecayRate = Mathf.Max(waveExponentialDecayRate, exponentialDecayRate);
			linearDecayRate = Mathf.Max(waveLinearDecayRate, linearDecayRate);

			waveExponentialDecayRate = 0;
			waveLinearDecayRate = 0;
		}

		public void OnBeforeSerialize()
		{

		}
	}
}