using System;
using UnityEngine;
using UnityEngine.Rendering;

namespace FluidFrenzy
{
	public static class CausticsEffect
	{
		/// <summary>
		/// Settings for all configurable visual parameters of the <see cref="CausticsEffect"/>.
		/// This class defines animated light patterns projected underwater, wave-driven highlights, and global visibility attenuation.
		/// </summary>
		/// <docgen-target>WaterSurfaceEditor</docgen-target>
		[Serializable]
		public class CausticsSettings
		{
			/// <summary>
			/// The playback speed of the animated caustics texture sequence.
			/// </summary>
			/// <remarks>
			/// Defines how many frames per second the texture advances. Higher values result in faster, smoother motion.
			/// </remarks>
			[Range(0, 120)]
			public float fps = 60.0f;

			/// <summary>
			/// Controls the scale of the projected caustics pattern.
			/// </summary>
			/// <remarks>
			/// Higher values increase the tiling frequency, making the pattern appear smaller and more dense across the environment.
			/// </remarks>
			public float tiling = 10.0f;

			/// <summary>
			/// Enables triplanar projection to prevent texture stretching on vertical surfaces.
			/// </summary>
			/// <remarks>
			/// Projects the texture from three orthogonal axes (X, Y, Z) instead of a single top-down projection. 
			/// Essential for maintaining pattern consistency on cliffs, walls, and steep underwater terrain.
			/// </remarks>
			public bool triplanar = false;

			/// <summary>
			/// The strength of the UV distortion applied to the caustics based on surface wave normals.
			/// </summary>
			/// <remarks>
			/// Simulates refractive warping by shifting the texture coordinates relative to the waves above.
			/// </remarks>
			[Range(0, 0.5f)]
			public float waveUVOffset = 0.01f;

			/// <summary>
			/// The brightness multiplier for the projected caustics texture.
			/// </summary>
			/// <remarks>
			/// An independent scalar specifically for the animated texture component of the effect.
			/// </remarks>
			[Range(0, 10)]
			public float textureIntensity = 1.0f;

			/// <summary>
			/// Defines which texture color channels contribute to the final caustics pattern.
			/// </summary>
			/// <remarks>
			/// Useful for isolating specific channels in packed textures.
			/// </remarks>
			public Vector4 channelMask = new Vector4(1, 1, 1, 1);

			/// <summary>
			/// The strength of the color splitting effect at the edges of the caustics.
			/// </summary>
			/// <remarks>
			/// Simulates light dispersion (prismatic effect), creating rainbow-like fringing around high-contrast areas of the pattern.
			/// </remarks>
			[Range(0, 0.05f)]
			public float chromaticAberration = 0.005f;

			/// <summary>
			/// The brightness of the procedural glints generated by surface wave curvature.
			/// </summary>
			/// <remarks>
			/// Unlike the texture projection, these highlights are calculated analytically from wave refraction to provide a direct link between the surface and the seafloor.
			/// </remarks>
			[Range(0, 10)]
			public float waveIntensity = 1.0f;

			/// <summary>
			/// Controls the focus and size of the procedural wave highlights.
			/// </summary>
			/// <remarks>
			/// Higher values result in sharper, thinner glints (lensing effect), while lower values create broader, softer highlights.
			/// </remarks>
			[Range(1, 50)]
			public float waveSharpness = 14.0f;

			/// <summary>
			/// A multiplier for all caustic lighting contributions.
			/// </summary>
			/// <remarks>
			/// Scales both the texture projection and the procedural wave highlights simultaneously.
			/// </remarks>
			[Range(0, 10)]
			public float globalIntensity = 1.0f;

			/// <summary>
			/// Controls how much the sea floor is darkened in the areas between light patterns.
			/// </summary>
			/// <remarks>
			/// Increasing this value darkens the "caustic shadows," making the bright light patterns appear more high-contrast and prominent.
			/// </remarks>
			[Range(0, 1)]
			public float darkness = 0.3f;

			/// <summary>
			/// Controls the visibility of caustics within areas shadowed by external light sources.
			/// </summary>
			/// <remarks>
			/// A value of 0 makes caustics completely invisible in shadow, while a value of 1 allows them to remain fully visible.
			/// </remarks>
			[Range(0, 1)]
			public float shadowIntensity = 0.3f;

			/// <summary>
			/// Defines the depth range near the surface where the caustics begin to appear.
			/// </summary>
			/// <remarks>
			/// The X value represents the depth where the effect starts, and the Y value is where it reaches full intensity. This prevents visual "popping" at the water line.
			/// </remarks>
			public Vector2 fadeInRange = new Vector2(0.1f, 1.0f);

			/// <summary>
			/// Defines the depth range where the caustics gradually disappear as light is absorbed.
			/// </summary>
			/// <remarks>
			/// The X value is the depth where fading begins, and the Y value is the depth where caustics are completely extinguished.
			/// </remarks>
			public Vector2 fadeOutRange = new Vector2(5.0f, 10.0f);

			/// <summary>
			/// Controls how much surface foam occludes the caustics on the seafloor.
			/// </summary>
			/// <remarks>
			/// Simulates the diffusive nature of bubbles. Thick foam scatters light, preventing sharp caustics from forming and casting a soft shadow on the environment below.
			/// </remarks>
			[Range(0, 5)]
			public float foamMasking = 0.5f;
		}

		private const string RESOURCES_PATH = "Caustics";
		private static readonly MaterialPropertyBlock s_Props = new MaterialPropertyBlock();
		private static Material s_CausticsMat;
		private static Texture2D[] s_CausticsTextures;
		private static bool s_TexturesLoaded = false;

		private static readonly int _CausticsTexture = Shader.PropertyToID("_CausticsTexture");
		private static readonly int _CausticsTiling = Shader.PropertyToID("_CausticsTiling");
		private static readonly int _CausticsWaveUVOffset = Shader.PropertyToID("_CausticsWaveUVOffset");
		private static readonly int _CausticsTextureIntensity = Shader.PropertyToID("_CausticsTextureIntensity");
		private static readonly int _CausticsWaveIntensity = Shader.PropertyToID("_CausticsWaveIntensity");
		private static readonly int _CausticsWaveSharpness = Shader.PropertyToID("_CausticsWaveSharpness");
		private static readonly int _CausticsGlobalIntensity = Shader.PropertyToID("_CausticsGlobalIntensity");
		private static readonly int _CausticsDarkness = Shader.PropertyToID("_CausticsDarkness");
		private static readonly int _CausticsShadowIntensity = Shader.PropertyToID("_CausticsShadowIntensity");
		private static readonly int _CausticsChromaOffset = Shader.PropertyToID("_CausticsChromaOffset");
		private static readonly int _CausticsFadeIn = Shader.PropertyToID("_CausticsFadeIn");
		private static readonly int _CausticsFadeOut = Shader.PropertyToID("_CausticsFadeOut");
		private static readonly int _CausticsChannelMask = Shader.PropertyToID("_CausticsChannelMask");
		private static readonly int _CausticsFoamMasking = Shader.PropertyToID("_CausticsFoamMasking");
		private static readonly int _InverseViewProjection = Shader.PropertyToID("_InverseViewProjection");

		private const string KEYWORD_DISPERSION = "_CAUSTICS_DISPERSION";
		private const string KEYWORD_TEXTURE_OFF = "_CAUSTICS_TEXTURE_OFF";
		private const string KEYWORD_FLOW_DYNAMIC = "_FLUID_FLOWMAPPING_DYNAMIC";
		private const string KEYWORD_FLOW_STATIC = "_FLUID_FLOWMAPPING_STATIC";
		private const string KEYWORD_TRIPLANAR = "_CAUSTICS_TRIPLANAR";
		private const string KEYWORD_FOAM = "_FOAMMASK_ON";

		private static Material GetMaterial()
		{
			if (s_CausticsMat == null)
			{
				Shader shader = Shader.Find("Hidden/FluidFrenzy/Caustics");
				if (shader != null) s_CausticsMat = new Material(shader);
			}
			return s_CausticsMat;
		}

		private static void LoadResources()
		{
			if (s_TexturesLoaded && s_CausticsTextures != null && s_CausticsTextures.Length > 0) return;
			s_CausticsTextures = Resources.LoadAll<Texture2D>(RESOURCES_PATH);
			System.Array.Sort(s_CausticsTextures, (a, b) => a.name.CompareTo(b.name));
			s_TexturesLoaded = true;
		}

		public static void Render(CommandBuffer cmd, Camera camera, WaterSurface surface)
		{
			if (surface == null || !surface.isActiveAndEnabled || !surface.IsCausticsEnabled) return;

			CausticsSettings settings = surface.causticsSettings ?? new CausticsSettings();
			Material mat = GetMaterial();
			if (mat == null) return;

			if (settings.textureIntensity > 0)
			{
				LoadResources();
				if (s_CausticsTextures != null && s_CausticsTextures.Length > 0)
				{
					int frameIndex = Mathf.FloorToInt(Time.time * settings.fps) % s_CausticsTextures.Length;
					mat.SetTexture(_CausticsTexture, s_CausticsTextures[frameIndex]);
					mat.DisableKeyword(KEYWORD_TEXTURE_OFF);
				}
				else mat.EnableKeyword(KEYWORD_TEXTURE_OFF);
			}
			else mat.EnableKeyword(KEYWORD_TEXTURE_OFF);

			if (settings.triplanar)
				mat.EnableKeyword(KEYWORD_TRIPLANAR);
			else
				mat.DisableKeyword(KEYWORD_TRIPLANAR);

			mat.SetFloat(_CausticsTiling, settings.tiling);
			mat.SetFloat(_CausticsWaveUVOffset, settings.waveUVOffset);
			mat.SetFloat(_CausticsTextureIntensity, settings.textureIntensity);
			mat.SetFloat(_CausticsWaveIntensity, settings.waveIntensity);
			mat.SetFloat(_CausticsWaveSharpness, settings.waveSharpness);
			mat.SetFloat(_CausticsGlobalIntensity, settings.globalIntensity);
			mat.SetFloat(_CausticsDarkness, settings.darkness);
			mat.SetFloat(_CausticsShadowIntensity, settings.shadowIntensity);
			mat.SetFloat(_CausticsChromaOffset, settings.chromaticAberration);
			mat.SetVector(_CausticsFadeIn, settings.fadeInRange);
			mat.SetVector(_CausticsFadeOut, settings.fadeOutRange);
			mat.SetVector(_CausticsChannelMask, settings.channelMask);

			if (settings.chromaticAberration > Mathf.Epsilon)
				mat.EnableKeyword(KEYWORD_DISPERSION);
			else
				mat.DisableKeyword(KEYWORD_DISPERSION);

			FluidFlowMapping flowMapping = surface.flowMapping;
			if (flowMapping != null && flowMapping.isActiveAndEnabled)
			{
				if (flowMapping.settings.flowMappingMode == FluidFlowMapping.FlowMappingMode.Dynamic)
				{
					mat.EnableKeyword(KEYWORD_FLOW_DYNAMIC);
					mat.DisableKeyword(KEYWORD_FLOW_STATIC);
				}
				else if (flowMapping.settings.flowMappingMode == FluidFlowMapping.FlowMappingMode.Static)
				{
					mat.EnableKeyword(KEYWORD_FLOW_STATIC);
					mat.DisableKeyword(KEYWORD_FLOW_DYNAMIC);
				}
				mat.SetVector(FluidShaderProperties._FlowBlend, flowMapping.flowBlend);
				mat.SetVector(FluidShaderProperties._FlowTimer, flowMapping.flowTime);
				mat.SetVector(FluidShaderProperties._FlowUVOffset, flowMapping.flowUVOffset);
				mat.SetVector(FluidShaderProperties._FlowSpeed, flowMapping.flowSpeed);
				mat.SetTexture(FluidShaderProperties._FluidUVOffsetField, flowMapping.activeLayer);
			}
			else
			{
				mat.DisableKeyword(KEYWORD_FLOW_DYNAMIC);
				mat.DisableKeyword(KEYWORD_FLOW_STATIC);
			}

			if (surface.foamLayer != null && settings.foamMasking > 0)
			{
				mat.EnableKeyword(KEYWORD_FOAM);
				mat.SetTexture(FluidShaderProperties._FluidFoamField, surface.foamLayer.activeLayer);
				mat.SetVector(FluidShaderProperties._FluidFoamField_ST, surface.foamLayer.textureST);
				mat.SetFloat(_CausticsFoamMasking, settings.foamMasking);
			}
			else
			{
				mat.DisableKeyword(KEYWORD_FOAM);
			}

			Matrix4x4 gpuProj = GL.GetGPUProjectionMatrix(camera.projectionMatrix, true);
			Matrix4x4 viewProj = gpuProj * camera.worldToCameraMatrix;
			mat.SetMatrix(_InverseViewProjection, viewProj.inverse);

			s_Props.Clear();
			UnderwaterShared.SetScreenSizeParam(s_Props, camera);
			FluidRenderPipeline.UpdateSurfaceProperties(s_Props, surface);

			CoreUtils.DrawFullScreen(cmd, mat, s_Props);
		}

		public static void Cleanup()
		{
			if (s_CausticsMat != null) GameObject.DestroyImmediate(s_CausticsMat);
			s_CausticsMat = null;
			s_CausticsTextures = null;
			s_TexturesLoaded = false;
		}
	}
}