using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using UnityEditor;
using UnityEngine;

namespace FluidFrenzy.Editor
{
#if UNITY_EDITOR
	[CustomEditor(typeof(FoamLayerSettings))]
	public class FoamLayerSettingsEditor : UnityEditor.Editor
	{
		private static class Styles
		{
			public static GUIContent renderingSettings = new GUIContent("Rendering Settings", "Control the rendering quality of the FoamLayer.");
			public static GUIContent decaySettings = new GUIContent("Decay Settings", "Control the decay rate of the foam in the FoamLayer mask.");

			public static GUIContent textureSizeText = new GUIContent(
				"Texture Size",
				@"The resolution of the generated foam mask texture.

Higher resolutions provide sharper foam details but require more memory and GPU processing power. It is generally recommended to match the aspect ratio of the fluid simulation grid."
			);
			public static GUIContent exponentialDecayRateText = new GUIContent(
				"Exponential Decay Rate",
				@"The rate at which pressure-based foam decays exponentially per frame.

Higher values cause the foam to dissipate more rapidly. This affects foam generated by the pressure system."
			);
			public static GUIContent linearDecayRateText = new GUIContent(
				"Linear Decay Rate",
				"The constant amount of pressure-based foam subtracted from the mask per frame (Linear Decay)."
			);

			public static GUIContent applyPressureFoamText = new GUIContent(
				"Pressure Foam",
				@"Toggles the generation of foam based on internal fluid pressure.

Note: This feature is strictly for use with FluxFluidSimulation. The alternative FlowFluidSimulation does not calculate internal pressure fields, so enabling this will have no effect in that mode."
			);
			public static GUIContent pressureRangeText = new GUIContent(
				"Range",
				@"Defines the pressure threshold range for foam generation.


•  X (Min): Pressure values below this threshold generate no foam. 
•  Y (Max): Pressure values above this threshold generate the maximum amount of foam. Intermediate values are interpolated using Smoothstep."
			);
			public static GUIContent pressureIncreaseAmountText = new GUIContent(
				"Amount",
				"The rate at which foam accumulates per frame when fluid pressure exceeds the pressureRange minimum."
			);

			public static GUIContent applyWaveFoamText = new GUIContent(
				"Wave Foam",
				@"Toggles the generation of foam based on wave geometry (height and steepness).

This system simulates whitecaps and crest foam caused by turbulent or high-amplitude waves."
			);
			public static GUIContent waveAngleRangeText = new GUIContent(
				"Angle Range",
				@"Defines the wave surface angle (steepness) thresholds for foam generation.


•  X (Min): Wave angles below this value generate no foam. 
•  Y (Max): Wave angles above this value generate maximum foam. Intermediate values are interpolated using Smoothstep."
			);
			public static GUIContent waveAngleIncreaseAmountText = new GUIContent(
				"Angle Amount",
				"The amount of foam added per frame when the wave angle exceeds the waveAngleRange minimum."
			);
			public static GUIContent waveHeightIncreaseAmountText = new GUIContent(
				"Height Amount",
				@"The amount of foam added per frame based on the vertical (Y) velocity of the fluid surface.

This simulates foam generated by rapidly rising water, such as splashes or chaotic wave peaks."
			);

			public static GUIContent applyShallowFoamText = new GUIContent(
				"Shallow Foam",
				@"Toggles the generation of foam in shallow water areas where fluid velocity is high.

This is useful for simulating shorelines or river rapids where water churns against the ground."
			);
			public static GUIContent shallowFoamAmountText = new GUIContent(
				"Amount",
				"The maximum intensity of foam added when the shallow water criteria are met."
			);
			public static GUIContent shallowVelocityRangeText = new GUIContent(
				"Velocity Range",
				@"Defines the velocity range required to generate foam in shallow water.


•  X (Min): Fluid speeds below this value generate no foam, even if the water is shallow. 
•  Y (Max): Fluid speeds above this value generate maximum foam. Intermediate values are interpolated using Smoothstep."
			);
			public static GUIContent shallowDepthText = new GUIContent(
				"Depth",
				@"The depth threshold for shallow water foam.

Foam will only be generated in areas where the fluid depth is less than this value (and velocity requirements are met)."
			);

			public static GUIContent applyTurbulenceFoamText = new GUIContent(
				"Turbulence Foam",
				@"Toggles the generation of foam based on velocity gradients (turbulence).

Calculates foam based on the curl or difference in velocity vectors between adjacent cells."
			);
			public static GUIContent turbulenceFoamAmountText = new GUIContent(
				"Amount",
				"The intensity multiplier for foam generated by turbulence."
			);
			public static GUIContent turbulenceFoamThresholdText = new GUIContent(
				"Threshold",
				"The minimum turbulence value required to begin generating foam."
			);
		}

		public static readonly int[] simulationCellCounts = { 32, 64, 128, 256, 512, 1024, 2048, 4096 };
		public static GUIContent[] simulationCellCountsName => simulationCellCounts.Select(x => new GUIContent(x.ToString())).ToArray();

		private SerializedProperty m_textureSizeProperty;
		private SerializedProperty m_applyPressureFoamProperty;

		private SerializedProperty m_pressureRangeProperty;

		private SerializedProperty m_pressureIncreaseAmountProperty;
		private SerializedProperty m_exponentialDecayRateProperty;
		private SerializedProperty m_linearDecayRateProperty;

		private SerializedProperty m_applyWaveFoamProperty;
		private SerializedProperty m_waveAngleRangeProperty;
		private SerializedProperty m_waveAngleIncreaseAmountProperty;
		private SerializedProperty m_waveHeightIncreaseAmountProperty;

		private SerializedProperty m_applyShallowFoamProperty;
		private SerializedProperty m_shallowFoamAmountProperty;
		private SerializedProperty m_shallowVelocityRangeProperty;
		private SerializedProperty m_shallowDepthProperty;

		private SerializedProperty m_applyTurbulenceFoamProperty;
		private SerializedProperty m_turbulenceFoamAmountProperty;
		private SerializedProperty m_turbulenceFoamThresholdProperty;

		private void OnEnable()
		{
			m_textureSizeProperty = serializedObject.FindProperty("textureSize");
			m_applyPressureFoamProperty = serializedObject.FindProperty("applyPressureFoam");

			m_pressureRangeProperty = serializedObject.FindProperty("pressureRange");

			m_pressureIncreaseAmountProperty = serializedObject.FindProperty("pressureIncreaseAmount");
			m_exponentialDecayRateProperty = serializedObject.FindProperty("exponentialDecayRate");
			m_linearDecayRateProperty = serializedObject.FindProperty("linearDecayRate");

			m_applyWaveFoamProperty = serializedObject.FindProperty("applyWaveFoam");
			m_waveAngleRangeProperty = serializedObject.FindProperty("waveAngleRange");
			m_waveAngleIncreaseAmountProperty = serializedObject.FindProperty("waveAngleIncreaseAmount");
			m_waveHeightIncreaseAmountProperty = serializedObject.FindProperty("waveHeightIncreaseAmount");

			m_applyShallowFoamProperty = serializedObject.FindProperty("applyShallowFoam");
			m_shallowFoamAmountProperty = serializedObject.FindProperty("shallowFoamAmount");
			m_shallowVelocityRangeProperty = serializedObject.FindProperty("shallowVelocityRange");
			m_shallowDepthProperty = serializedObject.FindProperty("shallowDepth");

			m_applyTurbulenceFoamProperty = serializedObject.FindProperty("applyTurbulenceFoam");
			m_turbulenceFoamAmountProperty = serializedObject.FindProperty("turbulenceFoamAmount");
			m_turbulenceFoamThresholdProperty = serializedObject.FindProperty("turbulenceFoamThreshold");
		}


		public override void OnInspectorGUI()
		{
			serializedObject.UpdateIfRequiredOrScript();

			EditorGUI.BeginChangeCheck();
			if(EditorExtensions.DrawFoldoutHeader(m_textureSizeProperty, Styles.renderingSettings))
			{
				EditorGUILayout.PropertyField(m_textureSizeProperty, Styles.textureSizeText);
				m_textureSizeProperty.vector2IntValue = Vector2Int.Max(FluidSimulation.kMinBufferSize, m_textureSizeProperty.vector2IntValue);
				m_textureSizeProperty.vector2IntValue = Vector2Int.Min(FluidSimulation.kMaxBufferSize, m_textureSizeProperty.vector2IntValue);
			}

			GUILayout.Space(5);
			if (EditorExtensions.DrawFoldoutHeader(m_exponentialDecayRateProperty, Styles.decaySettings))
			{
				EditorGUILayout.Slider(m_exponentialDecayRateProperty, 0, 1, Styles.exponentialDecayRateText);
				EditorGUILayout.Slider(m_linearDecayRateProperty, 0, 10, Styles.linearDecayRateText);
			}

			GUILayout.Space(5);
			if (EditorExtensions.DrawFoldoutHeaderToggle(m_applyPressureFoamProperty, Styles.applyPressureFoamText))
			{
				EditorGUILayout.PropertyField(m_pressureIncreaseAmountProperty, Styles.pressureIncreaseAmountText);
				EditorExtensions.MinMaxSlider(m_pressureRangeProperty, 0, 1, Styles.pressureRangeText);
			}

			GUILayout.Space(5);
			if (EditorExtensions.DrawFoldoutHeaderToggle(m_applyWaveFoamProperty, Styles.applyWaveFoamText))
			{
				EditorGUILayout.PropertyField(m_waveHeightIncreaseAmountProperty, Styles.waveHeightIncreaseAmountText);
				EditorGUILayout.PropertyField(m_waveAngleIncreaseAmountProperty, Styles.waveAngleIncreaseAmountText); 
				EditorExtensions.MinMaxSlider(m_waveAngleRangeProperty, -1, 1, Styles.waveAngleRangeText);
			}

			GUILayout.Space(5);
			if (EditorExtensions.DrawFoldoutHeaderToggle(m_applyShallowFoamProperty, Styles.applyShallowFoamText))
			{
				EditorGUILayout.PropertyField(m_shallowFoamAmountProperty, Styles.shallowFoamAmountText);
				EditorGUILayout.PropertyField(m_shallowDepthProperty, Styles.shallowDepthText);
				EditorExtensions.MinMaxSlider(m_shallowVelocityRangeProperty, 0, 10, Styles.shallowVelocityRangeText);
			}

			GUILayout.Space(5);
			if (EditorExtensions.DrawFoldoutHeaderToggle(m_applyTurbulenceFoamProperty, Styles.applyTurbulenceFoamText))
			{
				EditorGUILayout.PropertyField(m_turbulenceFoamAmountProperty, Styles.turbulenceFoamAmountText);
				EditorGUILayout.PropertyField(m_turbulenceFoamThresholdProperty, Styles.turbulenceFoamThresholdText);
			}

			if (EditorGUI.EndChangeCheck())
			{
				serializedObject.ApplyModifiedProperties();
			}
		}
	}
}
#endif